FROM openjdk:8u131-jdk-alpine

VOLUME /tmp

ADD target/authentication-service-1.0.0.war authentication-service.war

ENV JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=28787"

CMD java $JAVA_OPTS -jar /authentication-service.war --spring.profiles.active=docker
